config/routes.rb
Rails.application.routes.draw do
  
  get '/home' , to: "snacks#home" , as:"home"
  # get '/snacks' , to: "snacks#index", as:"snacks"
  # get '/snacks/:id' , to: "snacks#show" , as: "snack"

  resources :snacks  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snack.rb
class Snack < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  
  before_action :find_snack  , only: [:show , :edit , :update , :destroy]

  def home
  end 

  def index
  	@snacks = Snack.all 
  end

  def show
  end 

  def new
  	@snack = Snack.new
  end 

  def create
    snack = Snack.create(snack_strong_params)
    redirect_to snack_path(snack)
  end 

  def edit
  end 

  def update
  	@snack.update(snack_strong_params)
  	redirect_to snack_path(@snack)
  end 

  def destroy
  	@snack.delete
  	redirect_to snacks_path 
  end 

  def find_snack
  	@snack = Snack.find(params[:id])
  end 

  private 

  def snack_strong_params
  	params.require(:snack).permit(:name,:calories,:deliciousness)
  end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackTracking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/snacks/_snack_form.html.erb
	<%= form_for @snack do |f| %> 
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :calories %>
		<%= f.number_field :calories %>
		<%= f.label :deliciousness %>
		<%= f.select :deliciousness , (1..10) %>
		<%= f.submit  submit_text %>
	<% end %> 

app/views/snacks/edit.html.erb
<h1> Edit <%= @snack.name %></h1>

<%= render partial: "snack_form" , locals: {submit_text: "Edit this Snack" } %>

app/views/snacks/home.html.erb
<h1> Welcome to Our Super Snack App !! </h1>

<%= link_to "Enter Our App" , snacks_path %> 

app/views/snacks/index.html.erb
<h1>Snacks#index</h1>
<p>Find me in app/views/snacks/index.html.erb</p>

<ul>
	<% @snacks.each do |snack| %>
	<li> <%= link_to snack.name , snack_path(snack) %> </li>
	<% end %>
</ul>

<div><%= link_to "Create New Snack" , new_snack_path %></div>
<div><%= link_to "Home" , snacks_path %></div> 

app/views/snacks/new.html.erb
<h2> Create a New Snack </h2>

<%= render partial: "snack_form" , locals: {submit_text:"Create New Snack"} %>

app/views/snacks/show.html.erb
<h1> Details Page </h1>

<h2><%= @snack.name %></h2>

<h3> Calories: <%= @snack.calories %></h3>
<h3> Deliciousness : <%= @snack.deliciousness %></h3>

<%= link_to "Edit this Snack" , edit_snack_path(@snack) %>
<%= link_to "Delete this Snack" , snack_path(@snack) , :method => :delete , data: {:confirm => "Do You Really want to delete this snack ? "}%>
<%= link_to "Index Page" , snacks_path %>